const sendClient = require("./client/sendClient");
const receiveClient = require("./client/receiveClient");
let receive = new receiveClient("521999", "521999");

// 打印接收到的消息
receive.on("message", msg => {
    // msg.type表示消息类型
    // enter：进场消息、chatmsg：弹幕消息、dgb：送礼消息
    console.log(msg);
});


const  睫毛上的泪最美的炫舞= [
    {
        "domain": ".huya.com",
        "expirationDate": 1676471621,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__yamid_new",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "C940ECF606A00001B63912901BF818BA",
        "id": 1
    },
    {
        "domain": ".huya.com",
        "expirationDate": 1673879621,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__yamid_tt1",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "0.4380636719996065",
        "id": 2
    },
    {
        "domain": ".huya.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "__yaoldyyuid",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": true,
        "storeId": "0",
        "value": "1199569249314",
        "id": 3
    },
    {
        "domain": ".huya.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "__yasmid",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": true,
        "storeId": "0",
        "value": "0.4380636719996065",
        "id": 4
    },
    {
        "domain": ".huya.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "_rep_cnt",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": true,
        "storeId": "0",
        "value": "8",
        "id": 5
    },
    {
        "domain": ".huya.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "_yasids",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": true,
        "storeId": "0",
        "value": "__rootsid%3DC940EEDDCDC00001F211193555D0F830",
        "id": 6
    },
    {
        "domain": ".huya.com",
        "expirationDate": 1644938017,
        "hostOnly": false,
        "httpOnly": false,
        "name": "alphaValue",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "0.80",
        "id": 7
    },
    {
        "domain": ".huya.com",
        "expirationDate": 4766999623,
        "hostOnly": false,
        "httpOnly": false,
        "name": "game_did",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "3I8D8FTp06R8f4M7AhU9JBXeDVWIc74MU8w",
        "id": 8
    },
    {
        "domain": ".huya.com",
        "expirationDate": 1615994017,
        "hostOnly": false,
        "httpOnly": false,
        "name": "guid",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "0adb76ee868f2a608502660167014fe8",
        "id": 9
    },
    {
        "domain": ".huya.com",
        "expirationDate": 1614006718.856337,
        "hostOnly": false,
        "httpOnly": false,
        "name": "h_unt",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "1613401918",
        "id": 10
    },
    {
        "domain": ".huya.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "Hm_lpvt_51700b6c722f5bb4cf39906a596ea41f",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": true,
        "storeId": "0",
        "value": "1613402020",
        "id": 11
    },
    {
        "domain": ".huya.com",
        "expirationDate": 1644938020,
        "hostOnly": false,
        "httpOnly": false,
        "name": "Hm_lvt_51700b6c722f5bb4cf39906a596ea41f",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "1613399621",
        "id": 12
    },
    {
        "domain": ".huya.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "huya_flash_rep_cnt",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": true,
        "storeId": "0",
        "value": "73",
        "id": 13
    },
    {
        "domain": ".huya.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "huya_web_rep_cnt",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": true,
        "storeId": "0",
        "value": "210",
        "id": 14
    },
    {
        "domain": ".huya.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "huyawap_rep_cnt",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": true,
        "storeId": "0",
        "value": "28",
        "id": 15
    },
    {
        "domain": ".huya.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "huyaweb_rep_cnt",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": true,
        "storeId": "0",
        "value": "2",
        "id": 16
    },
    {
        "domain": ".huya.com",
        "expirationDate": 1644938017,
        "hostOnly": false,
        "httpOnly": false,
        "name": "isInLiveRoom",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "true",
        "id": 17
    },
    {
        "domain": ".huya.com",
        "expirationDate": 1644938017,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SoundValue",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "0.50",
        "id": 18
    },
    {
        "domain": ".huya.com",
        "expirationDate": 1615993608,
        "hostOnly": false,
        "httpOnly": false,
        "name": "udb_accdata",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "08615571698707",
        "id": 19
    },
    {
        "domain": ".huya.com",
        "expirationDate": 1614006408.772164,
        "hostOnly": false,
        "httpOnly": false,
        "name": "udb_biztoken",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "AQAxXG8Dyc6LxeqT2waeJ_T63mKE3WKJtEv_OLyUup5VKqKYI4BC2kIgAewE8rAly_WsNLZuueieyzM75ULul4ij85jz_k5_qr61ZZn247vHWbrJegB7hRHiMPBe6W7mOS_pEOXx-ADCQGZmCPy3qUOEaGhbaMJ1GhsmCjtqryqkptqszcnxDf5lnEebyXs-Lwu_qZsQvKoJY09nV1D1_uEtt7ZI-BTuIAOlQTesiug69X3-zL8riF4TEzpdT6MyWKsQRkXUMlqnmVe_Xy3u8qHYMfjNUWwD9YXMFrYkU1nH1r7sCJHK7pN6zzwWa2Ibwic4zsBU-yVdm9FGnyIyPsTv",
        "id": 20
    },
    {
        "domain": ".huya.com",
        "expirationDate": 1644935622,
        "hostOnly": false,
        "httpOnly": false,
        "name": "udb_guiddata",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "8f7ed6fdb0054640a9ac3fab8503bd9b",
        "id": 21
    },
    {
        "domain": ".huya.com",
        "expirationDate": 1614006408.772248,
        "hostOnly": false,
        "httpOnly": false,
        "name": "udb_origin",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "1",
        "id": 22
    },
    {
        "domain": ".huya.com",
        "expirationDate": 1614006408.772267,
        "hostOnly": false,
        "httpOnly": false,
        "name": "udb_other",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "%7B%22lt%22%3A%221613401608757%22%2C%22isRem%22%3A%221%22%7D",
        "id": 23
    },
    {
        "domain": ".huya.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "udb_passdata",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": true,
        "storeId": "0",
        "value": "3",
        "id": 24
    },
    {
        "domain": ".huya.com",
        "expirationDate": 1614006408.772285,
        "hostOnly": false,
        "httpOnly": false,
        "name": "udb_passport",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "hy_133336586",
        "id": 25
    },
    {
        "domain": ".huya.com",
        "expirationDate": 1614006408.7723,
        "hostOnly": false,
        "httpOnly": false,
        "name": "udb_status",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "1",
        "id": 26
    },
    {
        "domain": ".huya.com",
        "expirationDate": 1614006408.772317,
        "hostOnly": false,
        "httpOnly": false,
        "name": "udb_uid",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "1199569249314",
        "id": 27
    },
    {
        "domain": ".huya.com",
        "expirationDate": 1614006408.772333,
        "hostOnly": false,
        "httpOnly": false,
        "name": "udb_version",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "1.0",
        "id": 28
    },
    {
        "domain": ".huya.com",
        "expirationDate": 1614006408.77235,
        "hostOnly": false,
        "httpOnly": false,
        "name": "username",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "hy_133336586",
        "id": 29
    },
    {
        "domain": ".huya.com",
        "expirationDate": 1614006408.772363,
        "hostOnly": false,
        "httpOnly": false,
        "name": "yyuid",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "1199569249314",
        "id": 30
    },
    {
        "domain": "www.huya.com",
        "expirationDate": 1614006997,
        "hostOnly": true,
        "httpOnly": false,
        "name": "vplayer_sbanner_5668003_5668003",
        "path": "/521999",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "1",
        "id": 31
    }
]
const  Dongjak =[
    {
        "domain": ".huya.com",
        "expirationDate": 1670928705,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__yamid_new",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "C92C37B047600001B26612C0F6071671",
        "id": 1
    },
    {
        "domain": ".huya.com",
        "expirationDate": 1668336705,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__yamid_tt1",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "0.7535371900252492",
        "id": 2
    },
    {
        "domain": ".huya.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "__yaoldyyuid",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": true,
        "storeId": "0",
        "value": "1532745873",
        "id": 3
    },
    {
        "domain": ".huya.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "__yasmid",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": true,
        "storeId": "0",
        "value": "0.7535371900252492",
        "id": 4
    },
    {
        "domain": ".huya.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "_yasids",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": true,
        "storeId": "0",
        "value": "__rootsid%3DC940E14071200001FFCD1E10EC0B1320",
        "id": 5
    },
    {
        "domain": ".huya.com",
        "expirationDate": 1644939266,
        "hostOnly": false,
        "httpOnly": false,
        "name": "alphaValue",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "0.80",
        "id": 6
    },
    {
        "domain": ".huya.com",
        "expirationDate": 1613763497.682093,
        "hostOnly": false,
        "httpOnly": false,
        "name": "avatar",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "http://thirdqq.qlogo.cn/g?b=oidb&k=PNLiaJttBsf9SzuM3nhAH2A&s=640&t=1571917746",
        "id": 7
    },
    {
        "domain": ".huya.com",
        "expirationDate": 4766419740,
        "hostOnly": false,
        "httpOnly": false,
        "name": "game_did",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "rMTy4ZY9UJ6xtWjXKigNMALiLy9MkzLoSk1",
        "id": 8
    },
    {
        "domain": ".huya.com",
        "expirationDate": 1615995266,
        "hostOnly": false,
        "httpOnly": false,
        "name": "guid",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "0a42cc49ceac2160f29809010a0147f2",
        "id": 9
    },
    {
        "domain": ".huya.com",
        "expirationDate": 1614007485.525513,
        "hostOnly": false,
        "httpOnly": false,
        "name": "h_unt",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "1613402678",
        "id": 10
    },
    {
        "domain": ".huya.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "Hm_lpvt_51700b6c722f5bb4cf39906a596ea41f",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": true,
        "storeId": "0",
        "value": "1613403269",
        "id": 11
    },
    {
        "domain": ".huya.com",
        "expirationDate": 1644939268,
        "hostOnly": false,
        "httpOnly": false,
        "name": "Hm_lvt_51700b6c722f5bb4cf39906a596ea41f",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "1613079000,1613239882,1613311455,1613403216",
        "id": 12
    },
    {
        "domain": ".huya.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "huya_flash_rep_cnt",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": true,
        "storeId": "0",
        "value": "35",
        "id": 13
    },
    {
        "domain": ".huya.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "huya_web_rep_cnt",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": true,
        "storeId": "0",
        "value": "24",
        "id": 14
    },
    {
        "domain": ".huya.com",
        "expirationDate": 1644939266,
        "hostOnly": false,
        "httpOnly": false,
        "name": "isInLiveRoom",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "true",
        "id": 15
    },
    {
        "domain": ".huya.com",
        "expirationDate": 1613763497.68218,
        "hostOnly": false,
        "httpOnly": false,
        "name": "nickname",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "Dongjak",
        "id": 16
    },
    {
        "domain": ".huya.com",
        "expirationDate": 1613763497.682212,
        "hostOnly": false,
        "httpOnly": false,
        "name": "partner_uid",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "6895990A5729F7718D6A93B771399528",
        "id": 17
    },
    {
        "domain": ".huya.com",
        "expirationDate": 1644939266,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SoundValue",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "0.04",
        "id": 18
    },
    {
        "domain": ".huya.com",
        "expirationDate": 1613857820.7862,
        "hostOnly": false,
        "httpOnly": false,
        "name": "udb_biztoken",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "AQBijaDwDaYNrdysYhJeTZV7HsY5Xeu99jHxhMle0lonrAps7uB4WMHnRHg2BiUc6hYf8oqH_MLHTJqgebT2RGM5vIUQ3Ld4qSe_loyWqUbUk2Csz7upcL_SHw-c7n5bRoiUb6apBXsjSA7O_T0XU4OLHmhiUjf9LDTJhCC4yP9pCqd4CzMBozdcW-Xi2--79U3BtxgHpd_XYCzCegzm8GckiguNBF9Va3fftGDPp_HVsuZIUkhkuMQ4SYNbwTHPMEebcsE_3GrK73V7YqAA0ktuVWZeArNl3qxCs3HLTgyCclP1mLt1pdPTnloB8duxvk2R8ot1eixCLoKHU-yVH0hp",
        "id": 19
    },
    {
        "domain": ".huya.com",
        "expirationDate": 1639392719,
        "hostOnly": false,
        "httpOnly": false,
        "name": "udb_guiddata",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "e5b088f2bf6e42ecbe57fda68559679f",
        "id": 20
    },
    {
        "domain": ".huya.com",
        "expirationDate": 1613763497.682278,
        "hostOnly": false,
        "httpOnly": false,
        "name": "udb_openid",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "6895990A5729F7718D6A93B771399528",
        "id": 21
    },
    {
        "domain": ".huya.com",
        "expirationDate": 1613857820.786361,
        "hostOnly": false,
        "httpOnly": false,
        "name": "udb_origin",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "100",
        "id": 22
    },
    {
        "domain": ".huya.com",
        "expirationDate": 1613857820.786461,
        "hostOnly": false,
        "httpOnly": false,
        "name": "udb_other",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "%7B%22lt%22%3A%221613158695729%22%2C%22isRem%22%3A%221%22%7D",
        "id": 23
    },
    {
        "domain": ".huya.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "udb_passdata",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": true,
        "storeId": "0",
        "value": "3",
        "id": 24
    },
    {
        "domain": ".huya.com",
        "expirationDate": 1613857820.78652,
        "hostOnly": false,
        "httpOnly": false,
        "name": "udb_passport",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "newqq_e9gxzjq9q",
        "id": 25
    },
    {
        "domain": ".huya.com",
        "expirationDate": 1613857820.786563,
        "hostOnly": false,
        "httpOnly": false,
        "name": "udb_status",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "1",
        "id": 26
    },
    {
        "domain": ".huya.com",
        "expirationDate": 1613857820.786605,
        "hostOnly": false,
        "httpOnly": false,
        "name": "udb_uid",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "1532745873",
        "id": 27
    },
    {
        "domain": ".huya.com",
        "expirationDate": 1613857820.786707,
        "hostOnly": false,
        "httpOnly": false,
        "name": "udb_version",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "1.0",
        "id": 28
    },
    {
        "domain": ".huya.com",
        "expirationDate": 1613857820.786754,
        "hostOnly": false,
        "httpOnly": false,
        "name": "username",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "newqq_e9gxzjq9q",
        "id": 29
    },
    {
        "domain": ".huya.com",
        "expirationDate": 1644786907,
        "hostOnly": false,
        "httpOnly": false,
        "name": "videoBitRate",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "2000",
        "id": 30
    },
    {
        "domain": ".huya.com",
        "expirationDate": 1613857820.78678,
        "hostOnly": false,
        "httpOnly": false,
        "name": "yyuid",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "1532745873",
        "id": 31
    },
    {
        "domain": "www.huya.com",
        "expirationDate": 1614007663,
        "hostOnly": true,
        "httpOnly": false,
        "name": "vplayer_sbanner_5668003_5668003",
        "path": "/521999",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "1",
        "id": 32
    }
]
// 发送弹幕和送礼，需要设置cookies
let sender = new sendClient("521999", "521999", "Dongjak", Dongjak);


// 登录成功后进行发送弹幕和送礼
sender.on("loginSuccess", msg => {

    sender.sendMsg("哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈");
    /*setInterval(()=>{
        // 发送弹幕
        sender.sendMsg("せ影sんì、漫畫,快粜[三鯁sんì頻](мэ7э.χyz)Ж");
    },30000)*/
    /*// 登录成功1秒后，创建送礼订单
    setTimeout(() => {
        sender.getSequence();
    }, 1000);

    // 送礼订单创建成功时，进行送礼，礼物列表socket服务器会返回
    sender.on("getSequence", msg => {
        sender.consumeGift(msg.sSeq, "20114", 1);
    });*/
});

